### ISSUE TITLE
Encounter an error when building Py38DockerFile

### ISSUE THREAD

**Issue by madeinquant** [clj-python/libpython-clj#101]
Downloading https://files.pythonhosted.org/packages/03/27/e35e7c6e6a52fab9fcc64fc2b20c6b516eba930bb02b10ace3b38200d3ab/numpy-1.18.4-cp36-cp36m-manylinux1_x86_64.whl (20.2MB)
Installing collected packages: numpy
Successfully installed numpy-1.18.4
/**usr/local/bin/clj: line 6: echo: write error: Bad file descriptor**
The command '/bin/sh -c echo "deb http://fr.archive.ubuntu.com/ubuntu bionic main"

**Comment by cnuernber** [comment]
Are you still having this issue?  A lot of times this happens because docker fills up a volume and you need to clean out stale docker images:

https://docs.docker.com/config/pruning/

**Comment by madeinquant** [comment]
> Are you still having this issue? A lot of times this happens because docker fills up a volume and you need to clean out stale docker images:
> 
> https://docs.docker.com/config/pruning/

Thank you. I shall try over the next few days.

**Comment by cnuernber** [comment]
@madeinquant - Closing this for now.  Let me know if you are still having issues.
