### ISSUE TITLE
Bindings for clojure.java.io

### ISSUE THREAD

**Issue by piotr-yuxuan** [clj-python/libpython-clj#109]
Thank you very much for this awesome project. Given the pervasive high-quality of this project I was almost suprised that the following code fails:

``` clojure
(ns mwe
  (:require [libpython-clj.python :as py]
            [libpython-clj.require :as pyr]
            [clojure.java.io :as clj.io]))

(py/initialize!)
(pyr/require-python 'io)
(pyr/require-python 'pickle)

(with-open [rdr (clj.io/reader "./some/filepath")]
  (vec (pickle/load rdr)))

Execution error at libpython-clj.python.bridge/eval54323$fn (bridge.clj:1059).
Unable to convert objects of type: class java.io.BufferedReader
```

Of course this is not a blocking issue as it can be done that way:

``` clojure
(let [rdr (io/open "./some/filepath" "rb")]
  (type (pickle/load rdr)))
```

but I think it would be nice to have it. Would you accept to add it, or would you like to give pointers and accept PR regarding this?

**Comment by cnuernber** [comment]
I would definitely accept a PR, any time!

What python class is the analogue of a java.io reader?

**Comment by jjtolton** [comment]
I _believe_ the analogue would be [io.TextIOWrapper](https://docs.python.org/3/library/io.html#io.TextIOWrapper) but I'm not as familiar with how a [java reader](https://docs.oracle.com/javase/7/docs/api/java/io/Reader.html) works in practice.  However the `io.TextIOWrapper` is the type of the result of `open("/some/file")`.

**Comment by cnuernber** [comment]
So you would have a create a proxy implementation of io.TextIOWrapper that implemented the required functions by forwarding them to java.io.Reader - Seems tough :-).

**Comment by jjtolton** [comment]
Yep.  And this falls into one of those tough philosophical areas.  Although
it seems odd, how would we know that you didn't want to pass in a literal
`java.io.Reader` into a Python function for some reason?  i.e., perhaps
keeping track of a Python list or dictionary of these readers.  It's always
a tough balance.

**Comment by piotr-yuxuan** [comment]
note: for the interop to be complete, it should expose a `.close` method (like a clj-land file) so that `with-open` would work.

**Comment by jjtolton** [comment]
Interesting.  That would probably be an alias of the `__exit__` method from
Python.  There's already a `.close`, so perhaps that would suffice.

**Comment by cnuernber** [comment]
Closing this - it isn't clear any more that there is anything to be done here or that anyone has any interest in working on this.
