### ISSUE TITLE
Question: How to directing libpython-clj at a virtualenv (without activating it)

### ISSUE THREAD

**Issue by aeftimia** [clj-python/libpython-clj#111]
What would be the recommended way to directing libpython-clj to a virtualenv. I'm looking for a way without having to explicitly activate the virtualenv prior to running. It seems that calling `initialize!` would be the appropriate way to go. However it also seems like `initalize!` is called just upon `require`ing `libpython-clj.python` (without giving the user a chance to override it).

Thanks!

**Comment by cnuernber** [comment]
What has worked in the past has been having a clj file you know is loaded earlier than the rest of your system that calls [`libpython-clj.python/initialize!'](https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj/python.clj#L229).   

I personally strongly recommend using docker containers to control your environment.  We have an [example](https://github.com/cnuernber/facial-rec) of a docker container that mounts the local project directory as the current user and from there so you have access to all your local project data and code but your execution environment is more controlled.

**Comment by aeftimia** [comment]
I'd love to use a container, but the requirements of the project I'm working on don't allow that. The goal is to be able to package Python code within a Java project, and libpython-clj is my best (only?) option since Jython doesn't support 3+. I understand what you are saying about having a file loaded first that calls `initialize!`, but I still do not understand how to do so without importing `libpython-clj.python`. It's possible I'm misinterpreting what's going on, but it seems that just `require`ing `libpython-clj.python` triggers `initialize!`, and it doesn't seem like I can override that with another call to `initialize!` (I tried importing before and after the following block of code, and found both times I was able to import numpy.
```
(py/initialize!
  :java-library-path-addendum clojure.java.io/file python-path "lib"
  :exec-prefix python-path
  :executable python-path
  :prefix python-path
  :base-prefix python-path
  :base-exec-prefix python-path
  :python-home python-path
  :python-executable clojure.java.io/file python-path "bin/python")
```

`python-path` points to a blank virtual environment directory.

**Comment by aeftimia** [comment]
I'd love to use a container, but the requirements of the project I'm working on don't allow that. The goal is to be able to package Python code within a Java project, and libpython-clj is my best (only?) option since Jython doesn't support 3+. 

I learned about the `use` statement and got your suggestion working. Thanks!
