### ISSUE TITLE
libpython-clj performance issues.

### ISSUE THREAD

**Issue by zendevil** [clj-python/libpython-clj#112]
I have the following python code:
```

import cv2 as cv
import argparse
import tensorflow_datasets as tfds
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers
import time
import numexpr as ne
kitti_dir = "/Users/foo/Desktop/data_scene_flow"


img_height = 375
img_width = 1242

feature_size = 32

def decode_img(img):
  # convert the compressed string to a 3D uint8 tensor
  img = tf.image.decode_jpeg(img, channels=3)
  # resize the image to the desired size
  return tf.image.resize(img, [img_height, img_width])

left_ds = tf.data.Dataset.list_files(str(kitti_dir + "/training/image_2/*"), shuffle=False)
right_ds = tf.data.Dataset.list_files(str(kitti_dir + "/training/image_3/*"), shuffle=False)
num_elements = tf.data.experimental.cardinality(left_ds).numpy()
normalization_layer = tf.keras.layers.experimental.preprocessing.Rescaling(1./255)

start_time = time.time()

for l, r in zip(left_ds.take(num_elements), right_ds.take(num_elements)):
  print("")
print("end time is ", time.time() - start_time)

```

versus the following clojure:

```
(ns cv.core
  (:require [libpython-clj.require :refer [require-python]]
            [libpython-clj.python :refer [py* py. py.. py.- ->python] :as py]
            [clojure.string :as str]
            [tech.v2.datatype :as dtype]
            [criterium.core :refer [bench]]
            )
  (:import java.util.Base64))



(require-python 'cv2)
(require-python 'time)
(require-python '[tensorflow :as tf])
(require-python '[tensorflow_datasets :as tfds])
(require-python '[numpy :as np])

(def kitti-dir "/Users/foo/Desktop/data_scene_flow")




(defn decode-img [img]
  (let [img (py/call-kw (py. tf/io decode_image) [img] {:channels 3})]))



(defn train []

  (py/with-gil-stack-rc-context
    (let [left-ds (py* (py.- tf/data Dataset) list_files
                       [(str kitti-dir "/training/image_2/*")]
                       {:shuffle false})
          right-ds (py* (py.- tf/data Dataset) list_files
                        [(str kitti-dir "/training/image_3/*")]
                        {:shuffle false})
          num-elements (py.. tf/data -experimental (cardinality left-ds) numpy)

          normalization-layer
          (py.. tf/keras -layers -experimental -preprocessing (Rescaling (/ 1.0 255.0)))


          ]

      (def start-time (time/time))
      (doseq [l (py. left-ds take num-elements)
              r (py. right-ds take num-elements)]
        
        )
      (prn "end time is " (- (time/time) start-time))

)))
```

Where the python code takes 0.0410151481628418 seconds, the clojure code is taking 12.076033115386963 seconds, even after wrapping with an rc lock. What is causing the performance bottleneck and how can it be fixed?

**Comment by cnuernber** [comment]
I would venture to guess that marshaling small pieces of data across the language boundaries is causing the issue.  The best solution to this is the zero-copy mechanism for numpy arrays.

**Comment by jjtolton** [comment]
@zendevil I'll also point out that your `zip` and `doseq` are doing very different things.  What you mean to do is 
```
(time 
 (doseq [_ (map vec (py. left-ds take num-elements) (py. right-ds take num-elements))]))
```
The 
```
(doseq [ax a bx b])
```
is equivalent in Python to:
```
for a in ax:
    for b in bx:
```
which is very different in performance than `zip(ax, bx)`

Also I'd recommend using `time` instead of `def start-time` because the inline `def` is a huge drag on performance.

Depending on how many items you have, the time complexity could be accounting for the difference.

**Comment by jjtolton** [comment]
If you that doesn't change it the performance significantly and you're willing to share a `"/Users/foo/Desktop/data_scene_flow"`, I could try to replicate, I'm curious myself!

**Comment by zendevil** [comment]
@jjtolton, the data_scene_flow is taken from (Download stereo 2015/flow 2015/scene flow 2015 data set (2 GB)):
http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php
The kitti dataset is a popular benchmarking dataset for computer vision tasks.

**Comment by jjtolton** [comment]
`(time ...)` prints to the console.  If you need the return value, can always do

```
(with-out-str (time ...))
```
I assume this is just for benchmarking?

**Comment by jjtolton** [comment]
Thanks for the data.  I'm curious myself so I'll slot in some time Saturday to work a repro.

**Comment by cnuernber** [comment]
I don't think this is fixable with our current level of tech.  The JDK-16 pathway is going to be a bit faster but we can't call into python as fast as python can call into python; there is just too much to bridge there.
