### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by zendevil** [clj-python/libpython-clj#122]
Basically, many python libraries have overloaded operators. For example, in Pandas, you get the time delta between two times by doing:

```
dataframe.to_datetime("01/02/2020") - dataframe.to_datetime("01/01/2020")
```

Unfortunately, doing the following:

```
(- (to_datetime etc.) (to_datetime etc.))
```

doesn't yet work, gives:

```
. Caused by java.lang.ClassCastException
   libpython_clj.python.bridge$generic_python_as_jvm$reify__32765 cannot be cast
   to java.lang.Number
```

On the other hand, doing this:

```
((py/->python -) (to_datetime etc.) (to_datetime etc.))
```

gives:

```
Caused by java.lang.ClassCastException
   com.sun.jna.Pointer cannot be cast to clojure.lang.IFn
```

Is there anyway to overload the negative sign? The problem is that whatever the actual implemented function is that overloads the minus is buried somewhere in the source and isn't well known or meant to be exposed, it seems to  me. So how to do these basic operations?

**Comment by cnuernber** [comment]
We would need a namespace that redefines '-' in terms of the python "__minus__" attribute (and "__div__", etc).  Definitely doable.

**Comment by zendevil** [comment]
How can you please elaborate I don’t get it?

**Comment by sogaiu** [comment]
Perhaps some bits of what's here are being hinted at?

https://docs.python.org/3/library/operator.html

**Comment by cnuernber** [comment]
Closing.  This isn't a bug with libpython-clj but rather just needs someone to implement a namespace calling into the python functions themselves.
