### ISSUE TITLE
`run-simple-string` doesn't return `:result` keyword

### ISSUE THREAD

**Issue by cloojure** [clj-python/libpython-clj#129]
Tried a test:

```clojure
(py/run-simple-string "(2 + 3)") => 
{:globals
 {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>},
 :locals
 {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}}

```

**Comment by jjtolton** [comment]
What is the expected behavior here?  Sounds like you're expecting a `:result` key?

**Comment by jjtolton** [comment]
Ah, I see.  The documentation says there should be a `:result`.  This is no longer the case, we'll update the docstring.  

If you're looking for a result, you need to use the interop directly.  As an example:

```clojure
(require '[libpython-clj.requre :refer [require-python import-python]])
(require-python 'operator)
;;=> :ok
(operator/add 2 3) 
;;=> 5
```

**Comment by jjtolton** [comment]
@cloojure if you're encountering any issues with getting started, please feel free to stop by the Zulip chat (https://clojurians.zulipchat.com/#narrow/stream/215609-libpython-clj-dev) or continue to message here!

**Comment by cloojure** [comment]
OK, cool. Thanks for the tip about `operator/add`  I was wondering how to
do that!
Alan

**Comment by cnuernber** [comment]
I couldn't figure out how to get the last result left on the stack.  I really would like it to just return the result that was left on the stack but regardless the documentation was incorrect (fixed now, thank to JTolton).  Thanks for bringing this up!
