### ISSUE TITLE
new-to-clojure link is broken

### ISSUE THREAD

**Issue by daslu** [clj-python/libpython-clj#137]
https://github.com/clj-python/libpython-clj/blob/master/docs/new-to-clojure.md

It is an excellent post (I think), and we have used the link in various places 
(e.g. https://twitter.com/daslu_/status/1214968279162339330), 
so it may be useful to keep the link working.

**Comment by cnuernber** [comment]
Ah, in order to work with codox well I moved all the documents to 'topics'.

Here is the new link:
https://github.com/clj-python/libpython-clj/blob/master/topics/new-to-clojure.md
