### ISSUE TITLE
[macos] Upgrade from python 3.6 to 3.9, libpython-clj is still trying to load libpython3.6m.dylib

### ISSUE THREAD

**Issue by vxe** [clj-python/libpython-clj#138]
Here's the interaction

![libpython-clj](https://user-images.githubusercontent.com/4325947/100340187-a92c1780-2f8f-11eb-912b-84cf6abd1692.png)

Its not clear to me _why_ its trying to use 3.6 but I think the bug didn't surface before because the 3.6 dylib was still on disk, but homebrew decided it was time to delete it after the last run of `brew update`

Is there something cached that's I need to delete to get it to recognize my 3.9 install?

**Comment by cnuernber** [comment]
Nothing is cached but we have a bit of code that is meant to detect the python version that appears to be failing.

* [detect-startup-info](https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj/python/interpreter.clj#L152)
* [initialize](https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj/python/interpreter.clj#L442)

It appears detect-startup-info is not working for you.  What happens when you call this from the REPL?

**Comment by vxe** [comment]
`detect-startup-info` seems to returning 3.6 as a default

```
(libpython-clj.python.interpreter/detect-startup-info {})
{:python-home "/Library/Frameworks/Python.framework/Versions/3.6",
 :lib-version "3.6",
 :libname "python3.6m",
 :java-library-path-addendum
 "/Library/Frameworks/Python.framework/Versions/3.6/lib"}
```

when called with `:python-executable` for 3.9, its seems to spit out the right path for the dylib

```
user> (libpython-clj.python.interpreter/detect-startup-info {:python-executable "/usr/local/Cellar/python@3.9/3.9.0_2/bin/python3.9"})
{:python-home
 "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9",
 :lib-version "3.9",
 :libname "python3.9m",
 :java-library-path-addendum
 "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib"}
```

**Comment by cnuernber** [comment]
Well, the quick work around is to provide :python-executable to initialize! and be sure to be the first one to call initialize.  What happens if you attempt to tell the system exactly were the python executable is that you want it to use to setup it's library paths?

**Comment by vxe** [comment]
Might be related to the calling of `python3-config --prefix` as mentioned [here](https://github.com/clj-python/libpython-clj/blob/a4d23c14167845dde746373285b397a89d98b031/CHANGELOG.md#122) , which points to 3.6


```
╰─➛ python3-config --prefix                                                                                                                                    
/Library/Frameworks/Python.framework/Versions/3.6
```

there appears to be additional version specific commands now

```
╰─➛ python3.9-config --prefix                                                                                                                                  
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
```

**Comment by vxe** [comment]
^^ fixed the above with `brew cleanup && brew reinstall python@3.9`,  `detect-startup-info` now spits out the right values

```
user> (libpython-clj.python.interpreter/detect-startup-info {})
{:python-home
 "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9",
 :lib-version "3.9",
 :libname "python3.9m",
 :java-library-path-addendum
 "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib"}
```

however importing `require-python` still fails on attempting to load version 3.6 like in earlier screenshot, I think because of this bare call to[ (py/initialize!)](https://github.com/clj-python/libpython-clj/blob/a85be74de9385ba2ef0c01c78eb0c4045b9abd42/src/libpython_clj/metadata.clj#L13)


I see there was issue with the [pyregex creation in version 3.8](https://github.com/clj-python/libpython-clj/issues/98#issuecomment-629597244) , I am seeing a different failure related to a [potential platform key name issue](https://github.com/clj-python/libpython-clj/blob/a85be74de9385ba2ef0c01c78eb0c4045b9abd42/src/libpython_clj/python/interpreter.clj#L96)

```
user> (libpython-clj.python.interpreter/python-library-regex (libpython-clj.python.interpreter/python-system-info "/usr/local/bin/python3"))
Execution error (IllegalArgumentException) at libpython-clj.python.interpreter/python-library-regex (interpreter.clj:91).
No matching clause: :darwin
```

**Comment by cnuernber** [comment]
Does your PR completely address this issue for you?

**Comment by vxe** [comment]
yeah my issue seems to be resolved, I can now load `require-python` without any exceptions

**Comment by cnuernber** [comment]
OK, great closing :-).

**Comment by vxe** [comment]
@cnuernber is a new version with the changes going to be pushed to be pushed soon?  I'm using a local jar for testing but would more convenient to pull from clojars. thanks

**Comment by cnuernber** [comment]
For sure.

**Comment by cnuernber** [comment]
`2.00-alpha-6` is up.
