### ISSUE TITLE
Python modules visible from Lein REPL but not from emacs vim

### ISSUE THREAD

**Issue by paulakeen** [clj-python/libpython-clj#144]
Sorry if obvious, I'm new to Clojure...I am trying to use some Python libraries such as Pandas and Spacy in Clojure. I am using emacs and cider-jack-in. When copying exactly the same code in Lein REPL everything works fine. The same code in emacs fails to compile both when I use (require-python '[pandas :as p]) and (py/import-module "pandas"). The cider message is 
"Execution error at libpython-clj.python.interpreter/check-error-throw (interpreter.clj:499).
ModuleNotFoundError: No module named 'pandas'"...any help would be appreciated.

**Comment by cnuernber** [comment]
@paulakeen - Have you found an answer to your issue?  Sorry it took so long to get back to you.  Feel free to ping us at [zulip](https://clojurians.zulipchat.com/#narrow/stream/215609-libpython-clj-dev) or respond here for more help.

**Comment by cnuernber** [comment]
Closing this issue - Please reopen if issue still exists.
