### ISSUE TITLE
pickling in libpythin-clj fails in some scenarios

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#172]
In some scenarios the call `pickle/dump` done in Clojure fails.
One reason seems to be that the synthetic class `__jvm_io_bridge__` cannot be pickled.
See here: https://clojurians.zulipchat.com/#narrow/stream/215609-libpython-clj-dev/topic/pickle.20complex.20python.20object.20.3F

**Comment by cnuernber** [comment]
Is there a repro for this?

**Comment by behrica** [comment]
I cannot reproduce it anymore, for my case failing before.
I suppose it got solved in some form.
