### ISSUE TITLE
can we have cljbridge.py in pypi ?

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#178]
Not having it as a proper python module, makes some integrations difficult

**Comment by cnuernber** [comment]
Sure, nothing is stopping someone from doing that :-).

**Comment by behrica** [comment]
I gave it a first shot.
I am completely newby on python packages, but I manged to upload something on 
 the test-pypy https://test.pypi.org/simple/ 

The following command works for me on an empty virtual env and in an empty Docker after insalling python3 and java 7 clojure.

The package declares a dependency to `python-javabridge`

```bash
export JAVA_HOME=.....
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple  cljbridge

```

This might install `python-javabridge` which only works if JAVA_HOME is set.

inside python:

```python
from clojurebridge import cljbridge
cljbridge.init_jvm(start_repl=True,port=12345,bind='0.0.0.0')
```

@cnuernber , maybe you could try it out ones.
As I'm very new to python packages, I am not sure if I did a valid package.
I looks like it, at least

**Comment by behrica** [comment]
Code of the pacakge is here.
It uses "current cljbridge.py" from here:
https://github.com/clj-python/libpython-clj/blob/master/cljbridge.py

**Comment by behrica** [comment]
Once we have done this, we could go step further and make sure that the embedded repl start by python honors "deps.edn" and constructs the same classpath as a Clojure CLI would.
The needed pieces for this are here:

**Comment by behrica** [comment]
PR: https://github.com/clj-python/libpython-clj/pull/184

**Comment by behrica** [comment]
Done: https://pypi.org/project/cljbridge

**Comment by behrica** [comment]
can be closed
