### ISSUE TITLE
libpython crashes with core dump

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#182]
see discussion here: https://clojurians.zulipchat.com/#narrow/stream/215609-libpython-clj-dev/topic/core.20dump

I will provide repro with repoducible szenario soon.

**Comment by cnuernber** [comment]
This appears to be the same issue as #194.  

I wonder if something is initializing multiple interpreters and that is making take-gil behave differently.  Honestly the next step would be to carefully scan the code behind the python checkGil pathway and then with a debugger put memory watches on the mutex addresses.  Then load torch or this library and see what happens - my guess is the memory breakpoints will be hit quite a bit.  Perhaps we can do this outside of libpython-clj as the jvm itself causes quite a lot of annoying noise in the debugger.

In any case, closing this issue as it really is the same issue.
