### ISSUE TITLE
I tried cljbridge on FreeCAD & UPBGE

### ISSUE THREAD

**Issue by PlumpMath** [clj-python/libpython-clj#188]
FreeCAD shares memory between clojure n python, but can't access FreeCAD API,
Conversely, UPBGE & Blender can't share memory, but can access Blender API.

FreeCAD video : https://www.youtube.com/watch?v=IPX9heIwZ_o
UPBGE(blender) video : https://www.youtube.com/watch?v=bphlLY7zmX8

https://github.com/PlumpMath/freecad-cljbridge

The story is kind of long.
My original intention was...
I wanted to change the program using libpython-clj (clojure host) to cljbridge, which is python host.
Before yesterday, for mastery, we proceeded with freecad to test.
.
Originally, (https://github.com/tristanstraub/clj-python-trampoline))
I tested it with a blender-clj.
In purpose, I tried to operate the latest versions of libpython-clj and cljbridge, but they didn't work well.

First of all, to have a smooth interaction like the content of cljbridge,
When forced to set the python args option to "-r" to run the clojure-nrepl-server, the contents must be locked to blender-gui-repl to move on to the clojure-console-repl.
After that, data is never transferred to the emacs-cider. (Therefore, because "clj -r"... of course it can't be accessed directly from emacs.)

Because of that, I tried it with FreeCAD just in case. As expected, it run & connects well in freecad, and it interacts well with memory exposure.
Anyways.
python in Blender seems to be blocked internally can't interactive(-i options) mode.
.
(Likewise, the normal Python & cljbridge.py also when gave us the Python -i option, so we can "REPL" python-repl & clojure-repl both, )

maybe, 
Either in the blender or in the main() function of the code part that I modified cljbridge.py it's problem, and...
If caused by my misunderstanding of libpython-clj, what's the problem?
so I'll plan.. See more about tristanstraub/clj-python-trampoline,
and try to connect the blender to cljbridge again.

Blender 3.0 came out a few days ago.
I'm making a system related to 3D. my job..
My work that never ends, gui & web..
so easy I always just want to change to plug-in development work with these completed program modifications or expansion. like parasite.hehehe.. (But it's more so hard to do it with clojure...hee-ck)
anyway I am very interested in python-based 3D applications. (With my head &math &physics & speed & programming that doesn't work, it's so hard...In fact, I don't want to do everything related to 3D.) My goal is to make a 3d-tristan-pinball quake dune2 game with clojure, but... 
I feel like I'm going to die without not Completion anything. hahaha

**Comment by PlumpMath** [comment]
I've come to the strange conclusion that humanity can survive when RustPython and libpython-clj are combined.

**Comment by cnuernber** [comment]
combining all the things...
