### ISSUE TITLE
More correct to set `:python-home` from `sys.base_prefix`?

### ISSUE THREAD

**Issue by harishcm** [clj-python/libpython-clj#189]
Hi Chris,

Many thanks for your excellent library which is changing the Clojure landscape.

I recently had an issue with autodetection of `:python-home` in a virtual environment (built with either Poetry or venv) and solved it by (1) activating the virtual environment, (2) setting `$PYTHONHOME`, and (3) calling `lein $TASK` while inside the virtual environment.

Out of curiosity, I dug in further, and it seems to me that it may be more correct (at least to cover the use case of virtual environments) to autodetect `:python-home` from `sys.base_prefix` instead of the current `sys.prefix` as used in the library function `find-python-home`.

My reasoning:

[PEP 405 -- Python Virtual Environments][pep-405] specifies that for **virtual environments**, `sys.prefix` is changed to point relative to **site-packages**, while `sys.base_prefix` is set relative to the Python executable and the standard libraries.

[pep-405]: https://www.python.org/dev/peps/pep-0405/

![image](https://user-images.githubusercontent.com/159447/146889638-29174a9b-d947-47e8-9b21-c2489646495d.png)

In addition, this is also is also emphasized in the documentation for the `sys` module which states that when virtual environments are used, it is `sys.base_prefix` that remains pointing to the base Python installation (the one which the virtual environment was created from).

![image](https://user-images.githubusercontent.com/159447/146890379-4a449aea-9f8a-47f3-8701-1554bbce4d94.png)

![image](https://user-images.githubusercontent.com/159447/146890549-1226a615-f8fd-4e01-bb96-8d1dca82d4d7.png)

I tried the patched version of `find-python-home` below on my local machine with virtual environments (created by either Poetry or venv) and the autodetection of `:python-home` works properly.

    (defn find-python-home
      [system-info & [{:keys [python-home]}]]
      (cond
        python-home
        python-home
        (seq (System/getenv "PYTHONHOME"))
        (System/getenv "PYTHONHOME")
        :else
        (:base-prefix system-info))) ; change :prefix to :base-prefix

For your kind consideration. Many thanks!

**Comment by cnuernber** [comment]
This is great!  Solid argument- We should do it and see.

**Comment by harishcm** [comment]
Great to hear! If I could be of any help in the process/testing, please let me know what I could do :)

**Comment by jjtolton** [comment]
Why not make a PR? Would be more than welcome!

**Comment by harishcm** [comment]
Just sent a PR  #190 . My first one - hope it is alright. Many thanks!

**Comment by cnuernber** [comment]
Closed by #190
