### ISSUE TITLE
"python-executable = wrongPath" does not lead to an exception

### ISSUE THREAD

**Issue by subes** [clj-python/libpython-clj#192]
As discussed here: https://github.com/clj-python/libpython-clj/issues/191#issuecomment-1002154329
It might be of interest to look into why this code does not lead to an exception:
```
final Map<String, Object> initParams = new HashMap<>();
initParams.put("python-executable", "someWrongCommand");
libpython_clj2.java_api.initialize(initParams);
```

**Comment by cnuernber** [comment]
This should be fixed in latest version :-)

**Comment by subes** [comment]
Cool, was able to confirm in 2.006:
- wrongPath: does not work
- python2: does not work
- pypy: does not work
- python3: works!

Can thus be closed.
