### ISSUE TITLE
Issues with using libpython-clj with pyenv installed python version

### ISSUE THREAD

**Issue by bajrachar** [clj-python/libpython-clj#193]
OS: Arch 5.15.11-arch2-1
Libpython-clj 2.006
pyenv 2.2.3

I get a "Failed to find a valid python library!" when using a python library version set as global using pyenv [which is a different version from the system installed one]. It works fine when global is set to the system installed version.

Digging further into libpython-clj code, I found that it is actually trying to find the libpython.so file and the pyenv installed version only installs a libpython.a file.

It worked for me by forcing pyenv to generate a .so file -->
`$ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.5`

**Comment by jjtolton** [comment]
That’s great.  I can’t tell you how many times this has gotten me.  Glad to
finally see the proper installation pathway!

**Comment by thecontinium** [comment]
FYI: For those on a Mac with pyenv this also works 

e.g. 

``` sh
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.10.2
❯ pyenv root
/Users/blah/.cache/pyenv
```

``` clojure
(py/initialize! :python-executable "/Users/blah/.cache/pyenv/versions/3.10.2/bin/python"
                :library-path "/Users/blah/.cache/pyenv/versions/3.10.2/lib/libpython3.10.dylib")
```

**Comment by behrica** [comment]
can be closed ?

**Comment by cnuernber** [comment]
Yes - can be reopened as I am sure we will hear more about this
