### ISSUE TITLE
keyword lookup on NamedTuple

### ISSUE THREAD

**Issue by shaunlebron** [clj-python/libpython-clj#202]
I believe a [NamedTuple](https://docs.python.org/3.3/library/collections.html#namedtuple-factory-function-for-tuples-with-named-fields) in python supports two types of lookups: attribute name or index.

Right now, I have to use `(py.- nt :foo)` whereas `(:foo nt)` does not work and returns nil.  I believe this is because the jvm bridge is not able to treat a namedtuple as both a dict and a tuple.  Is this possible?

Thank you!

_(I deleted a followup comment about `(py. nt _asdict)` not working, but it was my error in not requiring "py.")_

**Comment by shaunlebron** [comment]
Also, while trying to convert a namedtuple to a dict using [`._asdict()`](https://docs.python.org/3/library/collections.html#collections.somenamedtuple._asdict), I had a peculiar run-in with the following two expressions which I presumed would be equivalent:
* `(py. nt _asdict)` fails with "unable to resolve classname: py"
* `((py.- nt _asdict))` succeeds

**Comment by jjtolton** [comment]
Clojure Keywords are not currently polymorphic with python __getattr__.

**Comment by jjtolton** [comment]
Did you require “py.”?

**Comment by shaunlebron** [comment]
Thanks. Is there a way to make keywords polymorphic to __getattr__ from the user side?

**Comment by jjtolton** [comment]
Do you mean extending libpython-clj itself?  We do have hooks into the
`datafy/nav` paradigm, which would be one option.  Checkout the code here:
https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj2/require.clj#L352

You could probably do something like:
```clojure
(defmethod pydafy 'builtins.NamedTuple [nt] ;; code to convert named tuple
-> clojure, possibly in conjunction ;; with a Clojure NamedTuple protocol
that extends `get` ... ) ``` note that once you've extended with `pydafy`,
you can then use standard Clojure `datafy` function. This would result in
code that might look like, at a low level, ```clojure (:foo (datafy nt))
``` There are lower level hooks available for performant marshalling of
data types from Python, but that would be a broader feature request
discussion.

**Comment by jjtolton** [comment]
Do you mean extending libpython-clj itself?  We do have hooks into the
`datafy/nav` paradigm, which would be one option.  Checkout the code here:
https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj2/require.clj#L352

You could probably do something like:

```clojure

(defmethod pydafy 'builtins.NamedTuple [nt] ;; code to convert named tuple
-> clojure, possibly in conjunction ;; with a Clojure NamedTuple protocol
that extends `get` ... ) 

``` 

note that once you've extended with `pydafy`,
you can then use standard Clojure `datafy` function. This would result in
code that might look like, at a low level, 

```clojure 

(:foo (datafy nt))

```

 There are lower level hooks available for performant marshalling of
data types from Python, but that would be a broader feature request
discussion.

**Comment by shaunlebron** [comment]
Thanks so much for the example, I was not familiar with `datafy`.  Glad to know this.

And just to share here, I missed the following distinction in Python (since they’re both equivalent in JS):
* `__getitem__` is for `foo['bar']` = `foo.get('bar')`
* `__getattr__` is for `foo.bar` = `getattr(foo, 'bar')`

So I understand your original response now, that keywords map to getitem, whereas `py.-` is to be used for getattr.  I’ll just use it that way to not hide what's happening in python.  Thank you!

**Comment by jjtolton** [comment]
Great point!  We're always discussing the right balance to strike in how
much to hide/expose.  Always open to suggestions, thank you for your input!

**Comment by shaunlebron** [comment]
Thanks. I don't really know what I'm doing yet, but I can't believe this project exists AND works flawlessly so far. Thanks for all your work 🙏
