### ISSUE TITLE
Exception bridging 

### ISSUE THREAD

**Issue by jjtolton** [clj-python/libpython-clj#21]
**Expected**:
```clojure 
(try
    (throw python/Exception)
    (catch python/Exception e 
      :win)) ;;=> :win 
```
**Actual**: :boom:

**Comment by jjtolton** [comment]
Not sure if this can be tackled low level or may need some combination of wrappers and macros, open area of research.

**Comment by jjtolton** [comment]
Closing for now due to lack of interest.

**Comment by bowbahdoe** [comment]
I want to chime in with some interest in at least carrying over exception type info in a way that is runtime accessable

**Comment by cnuernber** [comment]
Let's figure out a way to make this happen.  It was a solid suggestion.
