### ISSUE TITLE
requiring libpython-clj2.require initializes libpython-clj

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#223]
Calling

```
(require 'libpython-clj2.require)
```

calls (via `metadata`)  `py/initialize!` without parameters.
This is unexpected and defeats the existence of certain parameters to `initialize!`.

Maybe `initialize!!` could read a certain edn file on disk, and take parameters from there. (and not taking any parameters)

Then we could cleanly initialize lib-python very early.

**Comment by cnuernber** [comment]
I don't think statically linking will ever work - you still have python-path issues and then you would potentially be out of sync with numpy and any other c-based extension of python of which nearly all the really valuable ones are exactly that.  You would not work in most cases with conda or virtualenv.

We could refactor the metadata namespace to make the things it relies on delay-initialized and then remove the call to initialize!.  

More generally this issue and the issue with AOT projects is why the static code generation system exists, however.  So you can sort of trial things with require-python but then move to static code generation and locking python to a specific thread and such for production - both of which solve a host of issues but make repl-driven development less effective.

**Comment by jjtolton** [comment]
@behrica would a ` python.edn` solve this?  @cnuernber do we want to make that an option?

**Comment by jjtolton** [comment]
@behrica let me know if this would resolve the issue: https://github.com/clj-python/libpython-clj/pull/226

**Comment by behrica** [comment]
I think so.

My use case is a s well "libraries" which use libpython clj.
When and how to initialize lib-python clj is not obvoius.

Reading a local file could fix it, so every call to (py/initilize!) will reda the same file.
