### ISSUE TITLE
jdk-21 support ?

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#265]
on JDK-21-LTS, I get:
Caused by: java.lang.ClassNotFoundException: jdk.incubator.foreign.MemoryAddress

**Comment by behrica** [comment]
Maybe we are nearly there.
Using
 cnuernber/dtype-next {:mvn/version "10.116"}
 
 makes it  work to require libpython-clj

**Comment by cnuernber** [comment]
Yep dtype-next supports jdk-21 out of the box transparently
