### ISSUE TITLE
Support for kebab-case

### ISSUE THREAD

**Issue by jjtolton** [clj-python/libpython-clj#66]
Provide support for kebab case through the following `require-python` flags: 

```clojure 
(require-python '[libname :bind-case [:kebab :snake]])
(require-python '[libname :bind-case [:snake]])
(require-python '[libname :bind-case [:kebab]])
(require-python '[libname :kebab-case])
```

Ensure the following scenario is valid: 
```clojure
(ns a
  (:require ...))

(require-python '[csv :bind-ns :kebab-case])

(defn something-with-csv [& args]
  (csv/something-kebab args))
```
```clojure 
(ns b
  (:require [a :refer [something-with-csv]]  ...))

(require-python '[csv :bind-ns])

(defn something-else-with-csv [& args]
  (-> args (csv/something_with_snake_case) (partial apply something-with-csv)))
``` 

Cases default to Python with opt-in for kebab.  

This will allow the following API access:

```clojure
(require-python '[csv :bind-ns :bind-case [:snake :kebab]])

(csv/field_size_limit)
(csv/field-size-limit)
(py. csv field_size_limit)
(py. csv field-size-limit)
(py.. csv field-size-limit)
(py.. csv field_size_limit)
```

**Comment by jjtolton** [comment]
@cnuernber recommend closing for now due to complexity of implementation, possible confusion of API, and lack of interest

**Comment by zendevil** [comment]
I'm interested.

**Comment by jjtolton** [comment]
I've see you mention [concerns with performance](https://github.com/clj-python/libpython-clj/issues/114) in other places, @zendevil.  This change could potentially ding performance in order to make it backwards compatible.  Would it still be worth it?

**Comment by zendevil** [comment]
Maybe there could be an option to toggle camel case of to increase performance if needed.
