### ISSUE TITLE
Test datafy/nav functionality with REBL

### ISSUE THREAD

**Issue by cnuernber** [clj-python/libpython-clj#76]
As discussed [here](https://github.com/cnuernber/libpython-clj/pull/73).

We now have more or less generalized binding for python to datafy/nav.  We think, more or less :-).

If someone is so inclined, some testing/tutorials around annotating some python library and seeing what happens when they try to datafy/nav it via REBL would be cool.

**Comment by jelmerderonde** [comment]
Hi, just a quick note. Just started playing around with libpython-clj and came across this error when browsing some data in REBL:

```
Execution error (ExceptionInfo) at libpython-clj.require/eval33593$fn (require.clj:336).
datafy not implemented for builtins.list
```

Maybe this is not what you're looking for, but I thought it could help.

**Comment by cnuernber** [comment]
This is what we are looking for :-) - people testing with REBL :-).

**Comment by jjtolton** [comment]
I'm not actually all that familiar with REBL, could you provide some steps
to reproduce so I can check it out?  Thank you for picking this up!

**Comment by jelmerderonde** [comment]
I'm having trouble reproducing the issue. Once I encounter it again I will let you know!

**Comment by cnuernber** [comment]
Closing this; not high enough need/want to warrant leaving open.
