### ISSUE TITLE
Missing function signature

### ISSUE THREAD

**Issue by mattiasarro** [clj-python/libpython-clj#87]
Once again, amazing project!

I was experimenting if it's possible to use [flax](https://github.com/google-research/flax/tree/prerelease) with libpython-clj. I'm pretty much asking for trouble by combining these early-stage libraries, but it's just for fun. It seems that the code below fails because the function `apply` that libpython-clj defines on the fly does not have a [Function Signature Object](https://www.python.org/dev/peps/pep-0362/) associated with it, which `flax` tries to use via `inspect.signature`. Or I'm missing something in my Clojure code?

Just wondering if this is a known limitation, or there is a way to include this signature? Feel free to close the issue if this is not a top priority.

```clojure
(ns flax_model
  (:require [libpython-clj.require :refer [require-python]]
            [libpython-clj.python :as py]]))

(require-python '[flax.nn :as nn])

(def identity (py/create-class "Identity" [nn/Module]
                               {"apply" (py/make-tuple-instance-fn 
                                         (fn [self x] x)
                                         :arg-converter py/as-jvm
                                         :method-name "apply")}))
```

Stack trace:

```
Execution error at libpython-clj.python.interpreter/check-error-throw (interpreter.clj:474).
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flax/nn/base.py", line 169, in __init__
    apply_params = _fn_parameters(apply_fn)
  File "/usr/local/lib/python3.7/site-packages/flax/nn/base.py", line 153, in _fn_parameters
    return tuple(inspect.signature(fn).parameters.values())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 2288, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Py
thon.framework/Versions/3.7/lib/python3.7/inspect.py", line 2112, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function apply>

class clojure.lang.Compiler$CompilerException
```

**Comment by jjtolton** [comment]
I'm not as familiar with `flax` -- can you include the equivalent Python code so that I can try to repro?

**Comment by cnuernber** [comment]
@mattiasarro - Is this still an issue?

**Comment by mattiasarro** [comment]
@cnuernber We can close this issue, but I'm not sure if it's still a problem with newer versions of libpython-clj. I tried rerunning the example but the setup I had earlier to run libpython-clj doesn't work (I'm seeing the more general error `Syntax error compiling at (libpython_clj2/metadata.clj:17:1). Library not found.  Has set-library! been called?`).

I am using pyenv for my python installs, which doesn't play well with libpython-clj. So it's hard for me to reproduce the issue (no time to do it atm, but will come back to it once I have a spare moment).

**Comment by jjtolton** [comment]
@mattiasarro sorry that you're having issues with `pyenv`.  libpython-clj does support `pyenv` (see https://github.com/clj-python/libpython-clj/issues/96#issuecomment-629767514) but if you continue to experience issues let me know

**Comment by cnuernber** [comment]
@mattiasarro  - I added a [document on environments](https://clj-python.github.io/libpython-clj/environments.html) where we can collect our thoughts as python environments are difficult and we have had and will have many issues around them .  The one thing I remember is that pyenv users have to explicitly enable building the shared library.

**Comment by cnuernber** [comment]
Closing this for now - I am not sure it is fixed but there are conflicting notes above and we are limited in what we can do in this area.
