### ISSUE TITLE
Numpy / PyTorch Array Indexing and Slicing

### ISSUE THREAD

**Issue by stuartrexking** [clj-python/libpython-clj#88]
How do I do Numpy style array indexing and slicing?

Numpy arrays (and PyTorch tensors) let you operate on them directly and efficiently.

As an example, how would I do something like this?

```python
a[:, 5] += b[0] - a[:, 4].mean()
```

I don't want to do the indexing and slicing in the JVM. I want to do it in Python.

**Comment by zendevil** [comment]
There aren't any docs on np slicing and indexing syntax. Would you please share how you wrote this example in libpython-clj?

**Comment by cnuernber** [comment]
@zendevil - Now there is one very short document:

https://github.com/clj-python/libpython-clj/blob/master/docs/slicing.md

**Comment by zendevil** [comment]
There ought to be a concise way of indexing lists and numpy arrays. So far I haven't found any.

**Comment by jjtolton** [comment]
What do you propose?  Philosophically this is a grey area where user or
library code might make more sense than trying to add syntactic sugar for
such a specific operation, although I feel your pain.

**Comment by zendevil** [comment]
How about

```
(py/get-item ary [(builtins/slice 1 nil) (builtins/slice 1 nil)])
;; becomes

(py/get-item ary [[1 nil] [1 nil]])
```

The slicing functionality can be built into py/get-item

**Comment by cnuernber** [comment]
I agree that better support of slicing would be very cool.  Potentially this would just a be a macro that took input that looked exactly like the python slice syntax and then produced a vector of slice objects.

**Comment by zendevil** [comment]
I'd say having


```
(py/get-slice my-array [py/... [1 nil] [2 nil]])
```

where py/... is the Ellipses object, also very frequently used.
That would translate to:

```
my-array[..., 1:, 2:]
```

**Comment by sogaiu** [comment]
Regarding the legailty of `py[]` as a symbol name, I believe the claim that it is not valid is correct -- at least it's not likely to work in a straight-forward way for use with `def`, `defn`, and friends.

Accorrding to: https://clojure.org/reference/reader#_symbols:

> Symbols begin with a non-numeric character and can contain alphanumeric characters and *, +, !, -, _, ', ?, <, > and = (other characters may be allowed eventually).

Although these docs can be slightly off in some cases, I think they are correct in this case.

Also a repl started via `clj`:
```
user=> (def py[] nil)
Syntax error compiling def at (REPL:1:1).
Too many arguments to def
```
`def` doesn't succeed, and:
```
user=> (defn py[] [] nil)
#'user/py
```
`defn` ends up defining a function with a different name.

On a side note, there is this:
```
user=> (symbol "py[]")
py[]
user=> (type (symbol "py[]"))
clojure.lang.Symbol
```
But it's probably better to pretend we didn't see that :)

**Comment by jjtolton** [comment]
> But it's probably better to pretend we didn't see that :)
:rofl:

**Comment by jjtolton** [comment]
Are we sure a recipe wouldn't be better?  Otherwise I suppose it could go in the sugar section.

```clojure
(defn get-slice [x & args]
  (letfn [(slice
            ([] (python/slice nil nil))
            ([x] (if (vector? x)
                   (apply python/slice x)
                   x))
            ([x y & xs]
             (let [xs (into [x y] xs)]
               (if (every? int? xs)
                 (apply python/slice xs)
                 (mapv slice xs)))))]
    (py/get-item x (apply slice args))))
(get-slice (python/list [1 2 3]) 1 2) 
   => [2]
(require-python '[numpy :as np])

(get-slice (np/array [[1 2] [2 3] [3 4] [4 5] [6 5]]) [1 2] python/Ellipsis)
  => [[2 3]]

(get-slice (np/array [[1 2] [2 3] [3 4] [4 5] [6 5]]) [1 2] [1])
  => [[2]]

```
