### ISSUE TITLE
Can't import these libraries when pushing to production server.

### ISSUE THREAD

**Issue by zendevil** [clj-python/libpython-clj#92]
Steps to recreate:

1. Require the libraries like so:

(:require 
    [libpython-clj.require :refer [require-python]]
    [tech.v2.datatype :as dtype]

)

2. Then git add ., git commit -m "your message" and finally push to heroku using, for example, git push heroku master.

3. While the code is being pushed, it will terminate and fail to push, with the following error message:
```
remote:        Syntax error macroexpanding at (metadata.clj:13:1).        
remote:        Execution error (ExceptionInfo) at tech.jna.base/do-load-library (base.clj:158).        
remote:        Failed to load library        
```

Why is this, and how to fix this?

**Comment by kopos** [comment]
1. How are you deploying to the production server? As an uberjar?
2. Is there any other code in your Step 1?
3. Where are you seeing the error in Step 3? Are your console or on heroku?

**Comment by cnuernber** [comment]
Does the heroku server have python installed?  How are you controlling the heroku build/server environment?

Another problem here is going to be building the uberjar.  You have to delay calls to `require-python` till runtime; they can't happen at uberjar time (`aot: :all` can't happen, only `:aot [main.namespace]`). 


The tool I think helps here is https://clojuredocs.org/clojure.core/requiring-resolve.

**Comment by cnuernber** [comment]
@zendevil @kopos  - There is now [static code generation](https://clj-python.github.io/libpython-clj/libpython-clj2.codegen.html#var-write-namespace.21) so you can generate AOT-safe clojure namespaces once and then require them as needed.  They do not need python even at require time but only at runtime when called the first time.
