### ISSUE TITLE
Compatibility with older clojure version

### ISSUE THREAD

**Issue by Cartmanishere** [clj-python/libpython-clj#95]
Hi,

Is there any way to run this on a Clojure `1.8.0`.

**Comment by cnuernber** [comment]
Maybe, it might take some effort or removing features.  What is your use case for using 1.8 and not upgrading to 1.10?

**Comment by Cartmanishere** [comment]
I wanted to use it in a project which runs on Clojure 1.8. Of course, upgrade is an option. But if there is an easy way to use library on 1.8 as well, it would save a lot of trouble.

**Comment by cnuernber** [comment]
Honestly I haven't tried to compile `tech.datatype` with 1.8.  That would be the sticker; if that didn't work then there is no easy way.

**Comment by Cartmanishere** [comment]
I checked `tech.datatype` and `tech.parallel` from the perspective of running on clojure 1.8. 

More than them, I think the problematic part is that `require.clj` uses `datafy` and `nav` which isn't available on clojure 1.8.

Unfortunately after this exploration, I don't see a way to run this on clojure 1.8.

**Comment by Cartmanishere** [comment]
I was able to get it working on Clojure 1.8 after changing some code in `tech.parallel`, `tech.datatype` and `libpython-clj`.
